-- ALTER TABLE Smols ADD COLUMN Instrumental BOOLEAN DEFAULT 0;

DROP TABLE IF EXISTS Smols;

CREATE TABLE IF NOT EXISTS Smols (
    Id TEXT PRIMARY KEY,
    Title TEXT NOT NULL,
    Song_1 TEXT NOT NULL,
    Song_2 TEXT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Public BOOLEAN DEFAULT 1,
    Instrumental BOOLEAN DEFAULT 0,
    Plays INTEGER DEFAULT 0,
    Holders INTEGER DEFAULT 0,
    "Address" TEXT NOT NULL
);